version: '3.8'

services:
  # Neo4j Database
  neo4j:
    image: neo4j:5.11
    container_name: geni-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - geni-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: geni-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - geni-network

  # PostgreSQL (for user data and metadata)
  postgres:
    image: postgres:15-alpine
    container_name: geni-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: geni_clone
      POSTGRES_USER: geni_user
      POSTGRES_PASSWORD: geni_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geni-network

  # MinIO S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: geni-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - geni-network

  # RabbitMQ for message queuing
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: geni-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: geni
      RABBITMQ_DEFAULT_PASS: geni_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - geni-network

  # API Service
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: geni-api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://geni_user:geni_password@postgres:5432/geni_clone
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: geni_clone
      POSTGRES_USER: geni_user
      POSTGRES_PASSWORD: geni_password
      AWS_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      S3_BUCKET_NAME: geni-media
      RABBITMQ_URL: amqp://geni:geni_password@rabbitmq:5672
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    depends_on:
      - neo4j
      - redis
      - postgres
      - minio
      - rabbitmq
    networks:
      - geni-network
    restart: unless-stopped

  # UI Service
  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
    container_name: geni-ui
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    volumes:
      - ./apps/ui:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - geni-network
    restart: unless-stopped

  # Matching Service
  matching-service:
    build:
      context: ./services/matching
      dockerfile: Dockerfile
    container_name: geni-matching
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
      RABBITMQ_URL: amqp://geni:geni_password@rabbitmq:5672
    volumes:
      - ./services/matching:/app
      - /app/node_modules
    depends_on:
      - neo4j
      - redis
      - rabbitmq
    networks:
      - geni-network
    restart: unless-stopped

  # GEDCOM Service
  gedcom-service:
    build:
      context: ./services/gedcom
      dockerfile: Dockerfile
    container_name: geni-gedcom
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      REDIS_URL: redis://redis:6379
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
      RABBITMQ_URL: amqp://geni:geni_password@rabbitmq:5672
    volumes:
      - ./services/gedcom:/app
      - /app/node_modules
    depends_on:
      - neo4j
      - redis
      - rabbitmq
    networks:
      - geni-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  redis_data:
  postgres_data:
  minio_data:
  rabbitmq_data:

networks:
  geni-network:
    driver: bridge 